name: Run backend tests before master merge

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm run test:ci