name: Run backend tests before master merge

on:
  push:
    branches:
      - automatic-tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to ./backend
        run: cd backend

      - name: show files
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci